// Mocks generated by Mockito 5.4.6 from annotations
// in random_images/test/business_logic/cubit/random_image_cubit_test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:random_images/core/error/either.dart' as _i3;
import 'package:random_images/core/error/failures.dart' as _i6;
import 'package:random_images/domain/entities/random_image.dart' as _i7;
import 'package:random_images/domain/repositories/random_image_repository.dart'
    as _i2;
import 'package:random_images/domain/usecases/check_cache_status.dart' as _i12;
import 'package:random_images/domain/usecases/clear_cache.dart' as _i11;
import 'package:random_images/domain/usecases/get_cached_image.dart' as _i9;
import 'package:random_images/domain/usecases/get_random_image.dart' as _i4;
import 'package:random_images/domain/usecases/refresh_image.dart' as _i10;
import 'package:random_images/domain/usecases/usecase.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRandomImageRepository_0 extends _i1.SmartFake
    implements _i2.RandomImageRepository {
  _FakeRandomImageRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetRandomImage].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRandomImage extends _i1.Mock implements _i4.GetRandomImage {
  MockGetRandomImage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RandomImageRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRandomImageRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RandomImageRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.RandomImage>> call(
    _i8.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.RandomImage>>.value(
                  _FakeEither_1<_i6.Failure, _i7.RandomImage>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.RandomImage>>);
}

/// A class which mocks [GetCachedImage].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCachedImage extends _i1.Mock implements _i9.GetCachedImage {
  MockGetCachedImage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RandomImageRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRandomImageRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RandomImageRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.RandomImage>> call(
    _i8.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.RandomImage>>.value(
                  _FakeEither_1<_i6.Failure, _i7.RandomImage>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.RandomImage>>);
}

/// A class which mocks [RefreshImage].
///
/// See the documentation for Mockito's code generation for more information.
class MockRefreshImage extends _i1.Mock implements _i10.RefreshImage {
  MockRefreshImage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RandomImageRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRandomImageRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RandomImageRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.RandomImage>> call(
    _i8.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.RandomImage>>.value(
                  _FakeEither_1<_i6.Failure, _i7.RandomImage>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.RandomImage>>);
}

/// A class which mocks [ClearCache].
///
/// See the documentation for Mockito's code generation for more information.
class MockClearCache extends _i1.Mock implements _i11.ClearCache {
  MockClearCache() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RandomImageRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRandomImageRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RandomImageRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
              _FakeEither_1<_i6.Failure, bool>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}

/// A class which mocks [CheckCacheStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckCacheStatus extends _i1.Mock implements _i12.CheckCacheStatus {
  MockCheckCacheStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RandomImageRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRandomImageRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RandomImageRepository);

  @override
  _i5.Future<bool> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
