// Mocks generated by Mockito 5.4.6 from annotations
// in random_images/test/data/repositories/random_image_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:random_images/data/datasources/random_image_local_data_source.dart'
    as _i5;
import 'package:random_images/data/datasources/random_image_remote_data_source.dart'
    as _i3;
import 'package:random_images/data/models/random_image_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRandomImageModel_0 extends _i1.SmartFake
    implements _i2.RandomImageModel {
  _FakeRandomImageModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RandomImageRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRandomImageRemoteDataSource extends _i1.Mock
    implements _i3.RandomImageRemoteDataSource {
  MockRandomImageRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RandomImageModel> getRandomImage() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomImage, []),
            returnValue: _i4.Future<_i2.RandomImageModel>.value(
              _FakeRandomImageModel_0(
                this,
                Invocation.method(#getRandomImage, []),
              ),
            ),
          )
          as _i4.Future<_i2.RandomImageModel>);
}

/// A class which mocks [RandomImageLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRandomImageLocalDataSource extends _i1.Mock
    implements _i5.RandomImageLocalDataSource {
  MockRandomImageLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RandomImageModel?> getLastImage() =>
      (super.noSuchMethod(
            Invocation.method(#getLastImage, []),
            returnValue: _i4.Future<_i2.RandomImageModel?>.value(),
          )
          as _i4.Future<_i2.RandomImageModel?>);

  @override
  _i4.Future<void> cacheImage(_i2.RandomImageModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#cacheImage, [model]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> hasCachedImage() =>
      (super.noSuchMethod(
            Invocation.method(#hasCachedImage, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
