// Mocks generated by Mockito 5.4.6 from annotations
// in random_images/test/domain/usecases/get_random_image_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:random_images/core/error/either.dart' as _i2;
import 'package:random_images/core/error/failures.dart' as _i5;
import 'package:random_images/domain/entities/random_image.dart' as _i6;
import 'package:random_images/domain/repositories/random_image_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RandomImageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRandomImageRepository extends _i1.Mock
    implements _i3.RandomImageRepository {
  MockRandomImageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.RandomImage>> getRandomImage() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomImage, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.RandomImage>>.value(
                  _FakeEither_0<_i5.Failure, _i6.RandomImage>(
                    this,
                    Invocation.method(#getRandomImage, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.RandomImage>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.RandomImage>> getCachedImage() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedImage, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.RandomImage>>.value(
                  _FakeEither_0<_i5.Failure, _i6.RandomImage>(
                    this,
                    Invocation.method(#getCachedImage, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.RandomImage>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.RandomImage>> refreshImage() =>
      (super.noSuchMethod(
            Invocation.method(#refreshImage, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.RandomImage>>.value(
                  _FakeEither_0<_i5.Failure, _i6.RandomImage>(
                    this,
                    Invocation.method(#refreshImage, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.RandomImage>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#clearCache, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<bool> hasCachedImage() =>
      (super.noSuchMethod(
            Invocation.method(#hasCachedImage, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
